import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'architecture',
    'learner',
    'package-format',
    'package-authoring',
    'testing',
    {
      type: 'category',
      label: 'Design System',
      items: [
        {
          type: 'category',
          label: 'Primitives',
          items: [
            'components/primitives/accordion',
            'components/primitives/badge',
            'components/primitives/breadcrumb',
            'components/primitives/button',
            'components/primitives/card',
            'components/primitives/dialog',
            'components/primitives/drawer',
            'components/primitives/dropdown-menu',
            'components/primitives/empty-state',
            'components/primitives/input',
            'components/primitives/notification',
            'components/primitives/popover',
            'components/primitives/progress',
            'components/primitives/radio-group',
            'components/primitives/select',
            'components/primitives/skeleton',
            'components/primitives/spinner',
            'components/primitives/switch',
            'components/primitives/tabs',
            'components/primitives/tag',
            'components/primitives/textarea',
            'components/primitives/tooltip',
          ],
        },
        {
          type: 'category',
          label: 'Patterns',
          items: [
            'components/patterns/app-layout',
            'components/patterns/command-palette',
            'components/patterns/course-tree',
            'components/patterns/course-viewer-layout',
            'components/patterns/dashboard-layout',
            'components/patterns/settings-layout',
            'components/patterns/side-nav',
            'components/patterns/split-view',
            'components/patterns/three-panel-layout',
            'components/patterns/top-app-bar',
          ],
        },
        {
          type: 'category',
          label: 'Learning',
          items: [
            'components/learning/bundle-overview',
            'components/learning/completion-screen',
            'components/learning/concept-card',
            'components/learning/course-card',
            'components/learning/definition-block',
            'components/learning/lesson',
            'components/learning/module',
            'components/learning/progress-badge',
          ],
        },
        {
          type: 'category',
          label: 'AI',
          items: [
            'components/ai/ai-callout',
            'components/ai/ai-chat',
            'components/ai/ai-tutor-panel',
            'components/ai/citation',
            'components/ai/reference-card',
            'components/ai/suggested-questions',
            'components/ai/thinking-indicator',
            'components/ai/tutor-message',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      items: ['cli/overview'],
    },
    {
      type: 'category',
      label: 'Packages',
      items: ['schemas', 'accessibility', 'telemetry', 'rewards', 'runtime', 'dev-server', 'course-compiler'],
    },
    {
      type: 'category',
      label: 'Widgets',
      items: ['widgets/overview'],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/hello-world',
        'examples/intro-javascript',
        'examples/fractions',
        'examples/adaptive-study',
        'examples/autism-reading',
        'examples/living-vs-nonliving',
        'examples/skill-graph',
        'examples/widget-practice',
        'examples/widget-showcase',
        'examples/remote-widget-demo',
        'examples/level-b-math',
      ],
    },
  ],
};

export default sidebars;
