import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'architecture',
    'learner',
    'course-creator-studio',
    'package-format',
    'package-authoring',
    'agentic-authoring',
    {
      type: 'category',
      label: 'Widget Library',
      link: { type: 'doc', id: 'widget-library/getting-started' },
      items: [
        'widget-library/getting-started',
        {
          type: 'category',
          label: 'Core',
          items: [
            'widget-library/core/multiple-choice',
            'widget-library/core/matching',
            'widget-library/core/visual-counting',
            'widget-library/core/drag-drop',
            'widget-library/core/sequencing',
            'widget-library/core/fill-blank',
            'widget-library/core/story-question',
            'widget-library/core/real-world',
            'widget-library/core/chart-reader',
            'widget-library/core/callout',
            'widget-library/core/image-compare',
            'widget-library/core/hotspot',
            'widget-library/core/timeline',
            'widget-library/core/audio-player',
            'widget-library/core/process-explainer',
            'widget-library/core/video-player',
          ],
        },
        {
          type: 'category',
          label: 'Math',
          items: [
            'widget-library/math/fraction-visual',
            'widget-library/math/place-value-chart',
            'widget-library/math/grid-area',
            'widget-library/math/clock-time',
            'widget-library/math/measurement-scale',
            'widget-library/math/number-line',
          ],
        },
        {
          type: 'category',
          label: 'Science',
          items: [
            'widget-library/science/label-diagram',
            'widget-library/science/image-label',
            'widget-library/science/process-diagram',
          ],
        },
        {
          type: 'category',
          label: 'Language',
          items: ['widget-library/language/flashcard'],
        },
        {
          type: 'category',
          label: 'Social',
          items: ['widget-library/social/map'],
        },
      ],
    },
    'testing',
    {
      type: 'category',
      label: 'The OpenEdu Way',
      link: { type: 'doc', id: 'openedu-way/overview' },
      items: [
        {
          type: 'category',
          label: 'Volume I — Philosophy',
          link: { type: 'doc', id: 'openedu-way/philosophy/philosophy' },
          items: [
            'openedu-way/philosophy/philosophy',
            'openedu-way/philosophy/project-pipili',
            'openedu-way/philosophy/open-modules',
            'openedu-way/philosophy/the-companion',
            'openedu-way/philosophy/design-principles',
            'openedu-way/philosophy/temporal-design',
            'openedu-way/philosophy/motion-language',
          ],
        },
        'openedu-way/ai-context',
      ],
    },
    {
      type: 'category',
      label: 'Design System',
      items: [
        {
          type: 'category',
          label: 'Primitives',
          items: [
            'components/primitives/accordion',
            'components/primitives/badge',
            'components/primitives/breadcrumb',
            'components/primitives/button',
            'components/primitives/card',
            'components/primitives/dialog',
            'components/primitives/drawer',
            'components/primitives/dropdown-menu',
            'components/primitives/empty-state',
            'components/primitives/input',
            'components/primitives/notification',
            'components/primitives/popover',
            'components/primitives/progress',
            'components/primitives/radio-group',
            'components/primitives/select',
            'components/primitives/skeleton',
            'components/primitives/spinner',
            'components/primitives/switch',
            'components/primitives/tabs',
            'components/primitives/tag',
            'components/primitives/textarea',
            'components/primitives/tooltip',
          ],
        },
        {
          type: 'category',
          label: 'Patterns',
          items: [
            'components/patterns/app-layout',
            'components/patterns/command-palette',
            'components/patterns/course-tree',
            'components/patterns/course-viewer-layout',
            'components/patterns/dashboard-layout',
            'components/patterns/settings-layout',
            'components/patterns/side-nav',
            'components/patterns/split-view',
            'components/patterns/three-panel-layout',
            'components/patterns/top-app-bar',
          ],
        },
        {
          type: 'category',
          label: 'Learning',
          items: [
            'components/learning/bundle-overview',
            'components/learning/completion-screen',
            'components/learning/concept-card',
            'components/learning/course-card',
            'components/learning/definition-block',
            'components/learning/lesson',
            'components/learning/module',
            'components/learning/progress-badge',
          ],
        },
        {
          type: 'category',
          label: 'AI',
          items: [
            'components/ai/ai-callout',
            'components/ai/ai-chat',
            'components/ai/ai-tutor-panel',
            'components/ai/citation',
            'components/ai/reference-card',
            'components/ai/suggested-questions',
            'components/ai/thinking-indicator',
            'components/ai/tutor-message',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      items: ['cli/overview'],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        'schemas',
        'core',
        'workflow',
        'runtime',
        'accessibility',
        'telemetry',
        'rewards',
        'storage',
        'pwa-core',
        'pwa',
        'dev-server',
        'course-compiler',
        'pipeline',
        'llm-config',
        'ai-companion',
        'i18n',
        'oep-distribution',
        'registry',
        'widgets/overview',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/hello-world',
        'examples/intro-javascript',
        'examples/fractions',
        'examples/adaptive-study',
        'examples/autism-reading',
        'examples/living-vs-nonliving',
        'examples/skill-graph',
        'examples/widget-practice',
        'examples/widget-showcase',
        'examples/remote-widget-demo',
        'examples/level-b-math',
      ],
    },
  ],
};

export default sidebars;
