/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}', '../../packages/runtime/src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'var(--oe-color-surface)',
        'surface-dim': 'var(--oe-color-surface-dim)',
        'surface-bright': 'var(--oe-color-surface-bright)',
        'surface-container-lowest': 'var(--oe-color-surface-container-lowest)',
        'surface-container-low': 'var(--oe-color-surface-container-low)',
        'surface-container': 'var(--oe-color-surface-container)',
        'surface-container-high': 'var(--oe-color-surface-container-high)',
        'surface-container-highest': 'var(--oe-color-surface-container-highest)',
        'on-surface': 'var(--oe-color-on-surface)',
        'on-surface-variant': 'var(--oe-color-on-surface-variant)',
        'inverse-surface': 'var(--oe-color-inverse-surface)',
        'inverse-on-surface': 'var(--oe-color-inverse-on-surface)',
        outline: 'var(--oe-color-outline)',
        'outline-variant': 'var(--oe-color-outline-variant)',
        'surface-tint': 'var(--oe-color-surface-tint)',
        primary: 'var(--oe-color-primary)',
        'on-primary': 'var(--oe-color-on-primary)',
        'primary-container': 'var(--oe-color-primary-container)',
        'on-primary-container': 'var(--oe-color-on-primary-container)',
        'inverse-primary': 'var(--oe-color-inverse-primary)',
        secondary: 'var(--oe-color-secondary)',
        'on-secondary': 'var(--oe-color-on-secondary)',
        'secondary-container': 'var(--oe-color-secondary-container)',
        'on-secondary-container': 'var(--oe-color-on-secondary-container)',
        tertiary: 'var(--oe-color-tertiary)',
        'on-tertiary': 'var(--oe-color-on-tertiary)',
        'tertiary-container': 'var(--oe-color-tertiary-container)',
        'on-tertiary-container': 'var(--oe-color-on-tertiary-container)',
        error: 'var(--oe-color-error)',
        'on-error': 'var(--oe-color-on-error)',
        'error-container': 'var(--oe-color-error-container)',
        'on-error-container': 'var(--oe-color-on-error-container)',
        'primary-fixed': 'var(--oe-color-primary-fixed)',
        'primary-fixed-dim': 'var(--oe-color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--oe-color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--oe-color-on-primary-fixed-variant)',
        'secondary-fixed': 'var(--oe-color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--oe-color-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--oe-color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--oe-color-on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--oe-color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--oe-color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--oe-color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--oe-color-on-tertiary-fixed-variant)',
        background: 'var(--oe-color-background)',
        'on-background': 'var(--oe-color-on-background)',
        'surface-variant': 'var(--oe-color-surface-variant)',
      },
      fontFamily: {
        display: 'var(--oe-font-display-family)',
        'display-lg': 'var(--oe-font-display-family)',
        'headline-lg': 'var(--oe-font-headlineLg-family)',
        'headline-md': 'var(--oe-font-headlineMd-family)',
        title: 'var(--oe-font-title-family)',
        'body-lg': 'var(--oe-font-bodyLg-family)',
        'body-md': 'var(--oe-font-bodyMd-family)',
        'body-reading': 'var(--oe-font-bodyLg-family)',
        label: 'var(--oe-font-label-family)',
        'label-caps': 'var(--oe-font-label-family)',
        caption: 'var(--oe-font-caption-family)',
        mono: 'var(--oe-font-mono-family)',
      },
      fontSize: {
        'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['1.875rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h2: ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['2rem', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-reading': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body-ui': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['0.75rem', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        mono: ['0.8125rem', { lineHeight: '1.6', fontWeight: '400' }],
      },
      spacing: {
        base: 'var(--oe-space-base)',
        xs: 'var(--oe-space-xs)',
        sm: 'var(--oe-space-sm)',
        md: 'var(--oe-space-md)',
        lg: 'var(--oe-space-lg)',
        xl: 'var(--oe-space-xl)',
        gutter: 'var(--oe-space-gutter)',
        'margin-desktop': 'var(--oe-space-margin-desktop)',
        'margin-mobile': 'var(--oe-space-margin-mobile)',
        'container-max': 'var(--oe-space-container-max)',
        'panel-nav': 'var(--oe-space-panel-nav)',
        'panel-explorer': 'var(--oe-space-panel-explorer)',
      },
      borderRadius: {
        DEFAULT: 'var(--oe-radius-DEFAULT)',
        sm: 'var(--oe-radius-sm)',
        md: 'var(--oe-radius-md)',
        lg: 'var(--oe-radius-lg)',
        xl: 'var(--oe-radius-xl)',
        full: 'var(--oe-radius-full)',
      },
    },
  },
  plugins: [],
};
