import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface WidgetCatalogEntry {
  id: string;
  name?: string;
  description?: string;
  domain?: string;
  status?: string;
  deprecated?: boolean;
  replacement?: string;
  keywords?: string[];
  learningIntents?: string[];
  legacyId?: string;
  capabilities?: string[];
  accessibility?: string[];
  analytics?: string[];
  reward?: { completionXP?: number; positiveMessage?: string; achievement?: string };
  ai?: {
    difficulty?: string;
    estimatedMinutes?: number;
    bloomsLevel?: string;
    cognitiveLoad?: string;
    recommendedAge?: [number, number];
    readingLevel?: string;
    learningObjectives?: string[];
    commonMisconceptions?: string[];
    generationHints?: string[];
  };
}

export interface WidgetCatalogInput {
  widgets: WidgetCatalogEntry[];
}

export const WIDGET_ALIAS_MAP: Record<string, string> = {
  'open-edu.matching': 'core.matching',
  'open-edu.multiple-choice': 'core.multiple-choice',
  'open-edu.multiple-choice-practice': 'core.multiple-choice',
  'open-edu.visual-counting': 'core.visual-counting',
  'open-edu.drag-drop': 'core.drag-drop',
  'open-edu.sequencing': 'core.sequencing',
  'open-edu.fill-blank': 'core.fill-blank',
  'open-edu.story-question': 'core.story-question',
  'open-edu.real-world': 'core.real-world',
  'open-edu.fraction-visual': 'math.fraction-visual',
  'open-edu.place-value-chart': 'math.place-value-chart',
  'open-edu.grid-area': 'math.grid-area',
  'open-edu.chart-reader': 'core.chart-reader',
  'open-edu.clock-time': 'math.clock-time',
  'open-edu.measurement-scale': 'math.measurement-scale',
};

// Auto-generated by `pnpm --filter @open-edu/widgets generate:catalog`
// Source of truth: packages/widgets/src/widget-catalog-source.ts
const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_WIDGETS: WidgetCatalogEntry[] = JSON.parse(
  readFileSync(join(__dirname, 'widget-catalog-data.json'), 'utf-8'),
);

export function getDefaultWidgetCatalog(): string {
  return generateWidgetCatalog({ widgets: DEFAULT_WIDGETS });
}

export function generateWidgetCatalog(input: WidgetCatalogInput): string {
  const lines: string[] = [];
  lines.push('## Widget Catalog');
  lines.push('');
  lines.push(
    'The following built-in widgets are available. Each has a unique `widget` ID and expects a specific `config` object shape.',
  );
  lines.push(
    'Legacy `open-edu.*` IDs are automatically resolved to their new domain-prefixed equivalents.',
  );
  lines.push('');

  const byDomain = new Map<string, WidgetCatalogEntry[]>();

  for (const w of input.widgets) {
    const domain = w.domain || w.id.split('.')[0] || 'unknown';
    if (!byDomain.has(domain)) byDomain.set(domain, []);
    byDomain.get(domain)!.push(w);
  }

  const DOMAIN_LABELS: Record<string, string> = {
    core: 'Core Widgets',
    math: 'Math Widgets',
    language: 'Language Widgets',
    science: 'Science Widgets',
    social: 'Social Widgets',
  };

  for (const [domain, widgets] of byDomain) {
    lines.push(`### ${DOMAIN_LABELS[domain] ?? domain} Widgets`);
    lines.push('');

    for (const w of widgets) {
      let statusTag = '';
      if (w.status === 'deprecated') {
        statusTag = ' **[DEPRECATED]**';
      } else if (w.status === 'experimental') {
        statusTag = ' *(experimental)*';
      }

      lines.push(`#### ${w.name ?? w.id} (\`${w.id}\`)${statusTag}`);
      if (w.description) lines.push(w.description);
      lines.push('');

      if (w.learningIntents && w.learningIntents.length > 0) {
        const labels = w.learningIntents.map((i) => i.charAt(0).toUpperCase() + i.slice(1));
        lines.push(`Learning intents: ${labels.join(', ')}`);
        lines.push('');
      }

      if (w.legacyId) {
        lines.push(`Legacy ID: \`${w.legacyId}\` (auto-resolved)`);
        lines.push('');
      }

      if (w.deprecated && w.replacement) {
        lines.push(`Note: This widget is deprecated. Use \`${w.replacement}\` instead.`);
        lines.push('');
      }

      if (w.keywords && w.keywords.length > 0) {
        lines.push(`Keywords: ${w.keywords.join(', ')}`);
        lines.push('');
      }

      if (w.capabilities && w.capabilities.length > 0) {
        lines.push(`**Capabilities:** ${w.capabilities.join(', ')}`);
        lines.push('');
      }

      if (w.accessibility && w.accessibility.length > 0) {
        lines.push(`**Accessibility:** ${w.accessibility.join(', ')}`);
        lines.push('');
      }

      if (w.analytics && w.analytics.length > 0) {
        lines.push(`**Analytics:** ${w.analytics.join(', ')}`);
        lines.push('');
      }

      if (w.reward) {
        const parts: string[] = [];
        if (w.reward.completionXP) parts.push(`${w.reward.completionXP} XP`);
        if (w.reward.positiveMessage) parts.push(`"${w.reward.positiveMessage}"`);
        if (w.reward.achievement) parts.push(`achievement: ${w.reward.achievement}`);
        if (parts.length > 0) {
          lines.push(`**Rewards:** ${parts.join(', ')}`);
          lines.push('');
        }
      }

      if (w.ai) {
        lines.push('**AI Notes:**');
        if (w.ai.difficulty) lines.push(`- Difficulty: ${w.ai.difficulty}`);
        if (w.ai.estimatedMinutes) lines.push(`- Estimated time: ${w.ai.estimatedMinutes} min`);
        if (w.ai.bloomsLevel) lines.push(`- Bloom's: ${w.ai.bloomsLevel}`);
        if (w.ai.cognitiveLoad) lines.push(`- Cognitive load: ${w.ai.cognitiveLoad}`);
        if (w.ai.recommendedAge)
          lines.push(`- Ages: ${w.ai.recommendedAge[0]}-${w.ai.recommendedAge[1]}`);
        if (w.ai.readingLevel) lines.push(`- Reading level: ${w.ai.readingLevel}`);
        if (w.ai.learningObjectives && w.ai.learningObjectives.length > 0) {
          lines.push('- Learning objectives:');
          for (const obj of w.ai.learningObjectives) {
            lines.push(`  - ${obj}`);
          }
        }
        if (w.ai.commonMisconceptions && w.ai.commonMisconceptions.length > 0) {
          lines.push('- Common misconceptions:');
          for (const m of w.ai.commonMisconceptions) {
            lines.push(`  - ${m}`);
          }
        }
        if (w.ai.generationHints && w.ai.generationHints.length > 0) {
          lines.push('- Generation hints:');
          for (const h of w.ai.generationHints) {
            lines.push(`  - ${h}`);
          }
        }
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}
