import type { CurriculumProfile } from '../types.js';

export const MATH_PROFILE: CurriculumProfile = {
  id: 'math',
  subject: 'mathematics',
  locale: 'en-IN',
  language: 'en',
  sourceTaxonomy: {
    lessonLabels: ['Lesson', 'Chapter', 'Unit'],
    sectionLabels: ['Section'],
    objectiveLabels: ['Learning Objectives', 'Objectives'],
    definitionLabels: ['Definition'],
    exampleLabels: ['Example'],
    exerciseLabels: ['Exercise', 'Practice'],
    reviewLabels: ['Review', 'Summary'],
    assessmentLabels: ['Test', 'Assessment'],
  },
  conceptKinds: ['skill', 'knowledge', 'procedure', 'application'],
  representations: ['concrete', 'visual', 'symbolic'],
  questionFamilies: [
    'direct_computation',
    'word_problems',
    'real_world',
    'comparison',
    'estimation',
    'pattern_recognition',
    'true_false',
    'justification',
  ],
  widgetCategories: ['core', 'math'],
  assetRendererTypes: [
    'place-value-chart',
    'number-line',
    'fraction-bar',
    'fraction-circle',
    'decimal-grid',
    'measurement-scale',
    'area-grid',
    'perimeter-grid',
    'geometry-basic',
    'bar-chart',
    'pictograph',
  ],
  validatorIds: ['math'],
  promptContext: {
    teachingStyle: 'concrete -> visual -> symbolic (CPA approach)',
    includeAdultContext: true,
  },
};
