import type { ThemeDefinition } from '@open-edu/design-system';

export const forest: ThemeDefinition = {
  id: 'forest',
  name: 'Forest',
  description: 'Warm nature-inspired theme with earthy greens and browns.',
  colors: {
    surface: '#faf8f5',
    'surface-dim': '#e5e2dc',
    'surface-bright': '#ffffff',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f5f2ec',
    'surface-container': '#f0ede6',
    'surface-container-high': '#eae6df',
    'surface-container-highest': '#e5e0d9',
    'on-surface': '#1c1a17',
    'on-surface-variant': '#4a463f',
    'inverse-surface': '#322f2c',
    'inverse-on-surface': '#f5f2ec',
    outline: '#7a7670',
    'outline-variant': '#cbc6be',
    'surface-tint': '#3a5a38',
    primary: '#3a5a38',
    'on-primary': '#ffffff',
    'primary-container': '#b8d4b4',
    'on-primary-container': '#1a3a18',
    'inverse-primary': '#b8d4b4',
    secondary: '#5e6d56',
    'on-secondary': '#ffffff',
    'secondary-container': '#d6e4cc',
    'on-secondary-container': '#2a3d24',
    tertiary: '#7a6b4a',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#ddd0b0',
    'on-tertiary-container': '#3a2e14',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#d4eccf',
    'primary-fixed-dim': '#b8d4b4',
    'on-primary-fixed': '#0a2a08',
    'on-primary-fixed-variant': '#2a4a28',
    'secondary-fixed': '#d6e4cc',
    'secondary-fixed-dim': '#bac8b0',
    'on-secondary-fixed': '#1a2d14',
    'on-secondary-fixed-variant': '#3a4d34',
    'tertiary-fixed': '#ddd0b0',
    'tertiary-fixed-dim': '#c4b494',
    'on-tertiary-fixed': '#2a1e0a',
    'on-tertiary-fixed-variant': '#4a3a1a',
    background: '#faf8f5',
    'on-background': '#1c1a17',
    'surface-variant': '#e5e0d9',
    bg: '#faf8f5',
    fg: '#1c1a17',
    border: '#cbc6be',
    success: '#16a34a',
    ['success-container']: '#dafbe3',
    accent: '#5e6d56',
    ['primary-light']: '#b8d4b4',
  },
  typography: {
    productive: {
      display: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '44px',
        fontWeight: '700',
        lineHeight: '1.15',
        letterSpacing: '-0.01em',
      },
      heading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '28px',
        fontWeight: '650',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading4: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading5: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      heading6: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '14px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      body: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '14px',
        fontWeight: '420',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
    expressive: {
      display: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '44px',
        fontWeight: '700',
        lineHeight: '1.15',
        letterSpacing: '-0.01em',
      },
      heading: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '22px',
        fontWeight: '650',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading4: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      heading5: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '14px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      heading6: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '12px',
        fontWeight: '600',
        lineHeight: '1.6',
      },
      body: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '18px',
        fontWeight: '420',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk, system-ui, sans-serif',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '16px',
    containerMax: '720px',
    panelNav: '240px',
    panelExplorer: '320px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.25rem',
    DEFAULT: '0.625rem',
    md: '0.875rem',
    lg: '1.125rem',
    xl: '1.5rem',
    full: '9999px',
  },
};
