import { palette } from '@open-edu/design-system';
import type { ThemeDefinition } from '@open-edu/design-system';

export const forest: ThemeDefinition = {
  id: 'forest',
  name: 'Forest',
  description: 'Warm nature-inspired theme with earthy greens and browns.',
  colors: {
    surface: palette.sage95,
    'surface-dim': palette.sage83,
    'surface-bright': palette.sage95,
    'surface-container-lowest': palette.white,
    'surface-container-low': palette.sage92,
    'surface-container': palette.sage90,
    'surface-container-high': palette.sage88,
    'surface-container-highest': palette.sage85,
    'on-surface': palette.sage10,
    'on-surface-variant': palette.sage35,
    'inverse-surface': palette.sage20,
    'inverse-on-surface': palette.sage92,
    outline: palette.sage50,
    'outline-variant': palette.sage70,
    'surface-tint': palette.sage40,
    primary: palette.sage25,
    'on-primary': palette.white,
    'primary-container': palette.sage40,
    'on-primary-container': palette.sage80,
    'inverse-primary': palette.sage65,
    secondary: palette.sage38,
    'on-secondary': palette.white,
    'secondary-container': palette.sage78,
    'on-secondary-container': palette.sage15,
    tertiary: palette.bark35,
    'on-tertiary': palette.white,
    'tertiary-container': palette.bark70,
    'on-tertiary-container': palette.bark15,
    error: palette.red16,
    'on-error': palette.white,
    'error-container': palette.red88,
    'on-error-container': palette.red8,
    'primary-fixed': palette.sage80,
    'primary-fixed-dim': palette.sage65,
    'on-primary-fixed': palette.sage8,
    'on-primary-fixed-variant': palette.sage25,
    'secondary-fixed': palette.sage78,
    'secondary-fixed-dim': palette.sage75,
    'on-secondary-fixed': palette.sage5,
    'on-secondary-fixed-variant': palette.sage28,
    'tertiary-fixed': palette.bark75,
    'tertiary-fixed-dim': palette.bark70,
    'on-tertiary-fixed': palette.bark10,
    'on-tertiary-fixed-variant': palette.bark20,
    background: palette.sage95,
    'on-background': palette.sage10,
    'surface-variant': palette.sage85,
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '44px',
        fontWeight: '700',
        lineHeight: '1.15',
        letterSpacing: '-0.01em',
      },
      heading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      body: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      label: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '12px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.04em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '44px',
        fontWeight: '700',
        lineHeight: '1.15',
        letterSpacing: '-0.01em',
      },
      heading: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '22px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      body: {
        fontFamily: 'Source Serif 4',
        fontSize: '18px',
        fontWeight: '400',
        lineHeight: '1.7',
      },
      label: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '12px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.04em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '56px',
    marginMobile: '16px',
    containerMax: '800px',
    panelNav: '260px',
    panelExplorer: '320px',
    readingWidth: '65ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.25rem',
    DEFAULT: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    full: '9999px',
  },
};
