import type { ThemeDefinition } from './types';

export const highFocus: ThemeDefinition = {
  id: 'high-focus',
  name: 'High Focus',
  description:
    'Accessibility-first, high-contrast, structured minimalist. Removes visual noise with bold borders and generous negative space.',
  colors: {
    surface: '#fcf8f9',
    ['surface-dim']: '#dcd9da',
    ['surface-bright']: '#fcf8f9',
    ['surface-container-lowest']: '#ffffff',
    ['surface-container-low']: '#f6f3f4',
    ['surface-container']: '#f0edee',
    ['surface-container-high']: '#eae7e8',
    ['surface-container-highest']: '#e5e2e3',
    ['on-surface']: '#1b1b1c',
    ['on-surface-variant']: '#434653',
    ['inverse-surface']: '#303031',
    ['inverse-on-surface']: '#f3f0f1',
    outline: '#747685',
    ['outline-variant']: '#c4c5d6',
    ['surface-tint']: '#2a55c9',
    primary: '#002a81',
    ['on-primary']: '#ffffff',
    ['primary-container']: '#003eb3',
    ['on-primary-container']: '#a2b6ff',
    ['inverse-primary']: '#b5c4ff',
    secondary: '#046d3f',
    ['on-secondary']: '#ffffff',
    ['secondary-container']: '#9af3b8',
    ['on-secondary-container']: '#0f7142',
    tertiary: '#631700',
    ['on-tertiary']: '#ffffff',
    ['tertiary-container']: '#8a2501',
    ['on-tertiary-container']: '#ffa185',
    error: '#ba1a1a',
    ['on-error']: '#ffffff',
    ['error-container']: '#ffdad6',
    ['on-error-container']: '#93000a',
    ['primary-fixed']: '#dce1ff',
    ['primary-fixed-dim']: '#b5c4ff',
    ['on-primary-fixed']: '#00164e',
    ['on-primary-fixed-variant']: '#003cad',
    ['secondary-fixed']: '#9df5bb',
    ['secondary-fixed-dim']: '#81d9a0',
    ['on-secondary-fixed']: '#00210f',
    ['on-secondary-fixed-variant']: '#00522e',
    ['tertiary-fixed']: '#ffdbd1',
    ['tertiary-fixed-dim']: '#ffb59f',
    ['on-tertiary-fixed']: '#3a0a00',
    ['on-tertiary-fixed-variant']: '#862300',
    background: '#fcf8f9',
    ['on-background']: '#1b1b1c',
    ['surface-variant']: '#e5e2e3',
  },
  typography: {
    display: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '32px',
      fontWeight: '700',
      lineHeight: '1.2',
      letterSpacing: '-0.01em',
    },
    headlineLg: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '26px',
      fontWeight: '700',
      lineHeight: '1.2',
    },
    headlineMd: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '24px',
      fontWeight: '700',
      lineHeight: '1.3',
    },
    title: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '24px',
      fontWeight: '700',
      lineHeight: '1.3',
    },
    bodyLg: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '18px',
      fontWeight: '400',
      lineHeight: '1.6',
    },
    bodyMd: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '1.6',
    },
    label: {
      fontFamily: 'JetBrains Mono',
      fontSize: '14px',
      fontWeight: '500',
      lineHeight: '1.4',
      letterSpacing: '0.02em',
    },
    caption: {
      fontFamily: 'Atkinson Hyperlegible Next',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '1.4',
    },
    mono: {
      fontFamily: 'JetBrains Mono',
      fontSize: '14px',
      fontWeight: '500',
      lineHeight: '1.4',
      letterSpacing: '0.02em',
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '64px',
    marginMobile: '20px',
    containerMax: '1100px',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
