import type { ThemeDefinition } from '@open-edu/design-system';

export const highFocus: ThemeDefinition = {
  id: 'high-focus',
  name: 'High Focus',
  description:
    'Accessibility-first, high-contrast, structured minimalist. Removes visual noise with bold borders and generous negative space.',
  colors: {
    surface: '#fcfaf7',
    'surface-dim': '#dedbd8',
    'surface-bright': '#fcfaf7',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f6f4f0',
    'surface-container': '#f0ede9',
    'surface-container-high': '#eae7e3',
    'surface-container-highest': '#e5e2de',
    'on-surface': '#1c1b1a',
    'on-surface-variant': '#484642',
    'inverse-surface': '#31302e',
    'inverse-on-surface': '#f4f2ef',
    outline: '#757370',
    'outline-variant': '#c6c3be',
    'surface-tint': '#1a5acc',
    primary: '#003d8a',
    'on-primary': '#ffffff',
    'primary-container': '#1a5acc',
    'on-primary-container': '#d4e2ff',
    'inverse-primary': '#b5c8ff',
    secondary: '#1a7a50',
    'on-secondary': '#ffffff',
    'secondary-container': '#b8ecc8',
    'on-secondary-container': '#0a4a28',
    tertiary: '#7a2a10',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#b8603a',
    'on-tertiary-container': '#ffd4c4',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#dce5ff',
    'primary-fixed-dim': '#b5c8ff',
    'on-primary-fixed': '#001a4a',
    'on-primary-fixed-variant': '#00307a',
    'secondary-fixed': '#b8ecc8',
    'secondary-fixed-dim': '#82d0a0',
    'on-secondary-fixed': '#002a14',
    'on-secondary-fixed-variant': '#0a5a30',
    'tertiary-fixed': '#ffd4c4',
    'tertiary-fixed-dim': '#ffb098',
    'on-tertiary-fixed': '#3a0a00',
    'on-tertiary-fixed-variant': '#6a2010',
    background: '#fcfaf7',
    'on-background': '#1c1b1a',
    'surface-variant': '#e5e2de',
    bg: '#fcfaf7',
    fg: '#1c1b1a',
    border: '#c6c3be',
    success: '#16a34a',
    'success-container': '#dafbe3',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '32px',
        fontWeight: '700',
        lineHeight: '1.2',
        letterSpacing: '-0.01em',
      },
      heading: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '26px',
        fontWeight: '700',
        lineHeight: '1.2',
      },
      subheading: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '24px',
        fontWeight: '700',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '22px',
        fontWeight: '700',
        lineHeight: '1.3',
      },
      heading4: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading5: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading6: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      body: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '16px',
        fontWeight: '420',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'JetBrains Mono',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '1.4',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '14px',
        fontWeight: '500',
        lineHeight: '1.4',
        letterSpacing: '0.02em',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '32px',
        fontWeight: '700',
        lineHeight: '1.2',
        letterSpacing: '-0.01em',
      },
      heading: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '24px',
        fontWeight: '700',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '24px',
        fontWeight: '700',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '20px',
        fontWeight: '700',
        lineHeight: '1.3',
      },
      heading4: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading5: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading6: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '14px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      body: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '18px',
        fontWeight: '420',
        lineHeight: '1.6',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'JetBrains Mono',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Atkinson Hyperlegible Next',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '1.4',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '14px',
        fontWeight: '500',
        lineHeight: '1.4',
        letterSpacing: '0.02em',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '20px',
    containerMax: '720px',
    readingWidth: '70ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.375rem',
    md: '0.5rem',
    lg: '0.625rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
