import { palette } from '@open-edu/design-system';
import type { ThemeDefinition } from '@open-edu/design-system';

export const luminaScholastica: ThemeDefinition = {
  id: 'lumina-scholastica',
  name: 'Lumina Scholastica',
  description:
    'Modern minimalist learning environment with a content-first three-panel architecture.',
  colors: {
    surface: palette.purple99,
    ['surface-dim']: palette.gray75,
    ['surface-bright']: palette.purple99,
    ['surface-container-lowest']: palette.white,
    ['surface-container-low']: palette.gray92,
    ['surface-container']: palette.gray90,
    ['surface-container-high']: palette.gray85,
    ['surface-container-highest']: palette.gray80,
    ['on-surface']: palette.gray10,
    ['on-surface-variant']: palette.gray30,
    ['inverse-surface']: palette.gray20,
    ['inverse-on-surface']: '#f5eff7',
    outline: palette.gray40,
    ['outline-variant']: palette.gray50,
    ['surface-tint']: palette.purple30,
    primary: palette.purple20,
    ['on-primary']: palette.white,
    ['primary-container']: palette.purple30,
    ['on-primary-container']: '#e0d2ff',
    ['inverse-primary']: palette.purple80,
    secondary: '#63597c',
    ['on-secondary']: palette.white,
    ['secondary-container']: '#e1d4fd',
    ['on-secondary-container']: '#645a7d',
    tertiary: palette.amber40,
    ['on-tertiary']: palette.white,
    ['tertiary-container']: '#c9a74d',
    ['on-tertiary-container']: '#503d00',
    error: palette.red30,
    ['on-error']: palette.white,
    ['error-container']: palette.red90,
    ['on-error-container']: palette.red20,
    ['primary-fixed']: '#e9ddff',
    ['primary-fixed-dim']: palette.purple80,
    ['on-primary-fixed']: palette.purple10,
    ['on-primary-fixed-variant']: palette.purple20,
    ['secondary-fixed']: '#e9ddff',
    ['secondary-fixed-dim']: '#cdc0e9',
    ['on-secondary-fixed']: '#1f1635',
    ['on-secondary-fixed-variant']: '#4b4263',
    ['tertiary-fixed']: palette.amber80,
    ['tertiary-fixed-dim']: palette.amber60,
    ['on-tertiary-fixed']: '#241a00',
    ['on-tertiary-fixed-variant']: '#594400',
    background: palette.purple99,
    ['on-background']: palette.gray10,
    ['surface-variant']: palette.gray80,
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Inter',
        fontSize: '48px',
        fontWeight: '700',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter',
        fontSize: '30px',
        fontWeight: '600',
        lineHeight: '1.3',
        letterSpacing: '-0.01em',
      },
      subheading: {
        fontFamily: 'Inter',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading3: { fontFamily: 'Inter', fontSize: '20px', fontWeight: '600', lineHeight: '1.4' },
      heading4: { fontFamily: 'Inter', fontSize: '18px', fontWeight: '600', lineHeight: '1.4' },
      heading5: { fontFamily: 'Inter', fontSize: '16px', fontWeight: '500', lineHeight: '1.5' },
      heading6: { fontFamily: 'Inter', fontSize: '14px', fontWeight: '500', lineHeight: '1.5' },
      body: {
        fontFamily: 'Inter',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      label: {
        fontFamily: 'Inter',
        fontSize: '12px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.05em',
      },
      caption: {
        fontFamily: 'Inter',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '48px',
        fontWeight: '700',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Source Serif 4',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading3: { fontFamily: 'Source Serif 4', fontSize: '20px', fontWeight: '600', lineHeight: '1.4' },
      heading4: { fontFamily: 'Source Serif 4', fontSize: '18px', fontWeight: '600', lineHeight: '1.5' },
      heading5: { fontFamily: 'Source Serif 4', fontSize: '16px', fontWeight: '500', lineHeight: '1.6' },
      heading6: { fontFamily: 'Source Serif 4', fontSize: '14px', fontWeight: '500', lineHeight: '1.6' },
      body: {
        fontFamily: 'Source Serif 4',
        fontSize: '18px',
        fontWeight: '400',
        lineHeight: '1.7',
      },
      label: {
        fontFamily: 'Inter',
        fontSize: '12px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.05em',
      },
      caption: {
        fontFamily: 'Inter',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '64px',
    marginMobile: '20px',
    containerMax: '800px',
    panelNav: '260px',
    panelExplorer: '320px',
    readingWidth: '65ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
