import type { ThemeDefinition } from './types';

export const luminaScholastica: ThemeDefinition = {
  id: 'lumina-scholastica',
  name: 'Lumina Scholastica',
  description: 'Modern minimalist learning environment with a content-first three-panel architecture.',
  colors: {
    surface: '#fdf7ff',
    ['surface-dim']: '#ded8e0',
    ['surface-bright']: '#fdf7ff',
    ['surface-container-lowest']: '#ffffff',
    ['surface-container-low']: '#f8f2fa',
    ['surface-container']: '#f2ecf4',
    ['surface-container-high']: '#ece6ee',
    ['surface-container-highest']: '#e6e0e9',
    ['on-surface']: '#1d1b20',
    ['on-surface-variant']: '#494551',
    ['inverse-surface']: '#322f35',
    ['inverse-on-surface']: '#f5eff7',
    outline: '#7a7582',
    ['outline-variant']: '#cbc4d2',
    ['surface-tint']: '#6750a4',
    primary: '#4f378a',
    ['on-primary']: '#ffffff',
    ['primary-container']: '#6750a4',
    ['on-primary-container']: '#e0d2ff',
    ['inverse-primary']: '#cfbcff',
    secondary: '#63597c',
    ['on-secondary']: '#ffffff',
    ['secondary-container']: '#e1d4fd',
    ['on-secondary-container']: '#645a7d',
    tertiary: '#765b00',
    ['on-tertiary']: '#ffffff',
    ['tertiary-container']: '#c9a74d',
    ['on-tertiary-container']: '#503d00',
    error: '#ba1a1a',
    ['on-error']: '#ffffff',
    ['error-container']: '#ffdad6',
    ['on-error-container']: '#93000a',
    ['primary-fixed']: '#e9ddff',
    ['primary-fixed-dim']: '#cfbcff',
    ['on-primary-fixed']: '#22005d',
    ['on-primary-fixed-variant']: '#4f378a',
    ['secondary-fixed']: '#e9ddff',
    ['secondary-fixed-dim']: '#cdc0e9',
    ['on-secondary-fixed']: '#1f1635',
    ['on-secondary-fixed-variant']: '#4b4263',
    ['tertiary-fixed']: '#ffdf93',
    ['tertiary-fixed-dim']: '#e7c365',
    ['on-tertiary-fixed']: '#241a00',
    ['on-tertiary-fixed-variant']: '#594400',
    background: '#fdf7ff',
    ['on-background']: '#1d1b20',
    ['surface-variant']: '#e6e0e9',
  },
  typography: {
    display: {
      fontFamily: 'Inter',
      fontSize: '48px',
      fontWeight: '700',
      lineHeight: '1.1',
      letterSpacing: '-0.02em',
    },
    headlineLg: {
      fontFamily: 'Inter',
      fontSize: '30px',
      fontWeight: '600',
      lineHeight: '1.3',
      letterSpacing: '-0.01em',
    },
    headlineMd: {
      fontFamily: 'Inter',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '1.3',
    },
    title: {
      fontFamily: 'Inter',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '1.3',
    },
    bodyLg: {
      fontFamily: 'Source Serif 4',
      fontSize: '18px',
      fontWeight: '400',
      lineHeight: '1.7',
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '1.5',
    },
    label: {
      fontFamily: 'Inter',
      fontSize: '12px',
      fontWeight: '600',
      lineHeight: '1.0',
      letterSpacing: '0.05em',
    },
    caption: {
      fontFamily: 'Inter',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '1.5',
    },
    mono: {
      fontFamily: 'JetBrains Mono',
      fontSize: '13px',
      fontWeight: '400',
      lineHeight: '1.6',
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '64px',
    marginMobile: '20px',
    containerMax: '800px',
    panelNav: '260px',
    panelExplorer: '320px',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
