import type { ThemeDefinition } from '@open-edu/design-system';

export const luminaScholastica: ThemeDefinition = {
  id: 'lumina-scholastica',
  name: 'OpenEdu Light',
  description: 'Default calm theme for everyday learning.',
  colors: {
    surface: '#fcfaf8',
    ['surface-dim']: '#e3dfda',
    ['surface-bright']: '#fefcf9',
    ['surface-container-lowest']: '#ffffff',
    ['surface-container-low']: '#f7f4f0',
    ['surface-container']: '#f2eee9',
    ['surface-container-high']: '#ebe7e2',
    ['surface-container-highest']: '#e4dfda',
    ['on-surface']: '#1f1c18',
    ['on-surface-variant']: '#48443f',
    ['inverse-surface']: '#322f2c',
    ['inverse-on-surface']: '#f5f2ef',
    outline: '#76706b',
    ['outline-variant']: '#ccc6c0',
    ['surface-tint']: '#7c6bb0',
    primary: '#5d4a8a',
    ['on-primary']: '#ffffff',
    ['primary-container']: '#7c6bb0',
    ['on-primary-container']: '#ede2ff',
    ['inverse-primary']: '#d4c4ff',
    secondary: '#665e77',
    ['on-secondary']: '#ffffff',
    ['secondary-container']: '#e8dff7',
    ['on-secondary-container']: '#655d77',
    tertiary: '#b8862d',
    ['on-tertiary']: '#ffffff',
    ['tertiary-container']: '#f0d68a',
    ['on-tertiary-container']: '#4a3800',
    error: '#ba1a1a',
    ['on-error']: '#ffffff',
    ['error-container']: '#ffdad6',
    ['on-error-container']: '#93000a',
    ['on-success']: '#ffffff',
    ['on-success-container']: '#003914',
    ['primary-fixed']: '#ede2ff',
    ['primary-fixed-dim']: '#d4c4ff',
    ['on-primary-fixed']: '#2a104d',
    ['on-primary-fixed-variant']: '#5d4a8a',
    ['secondary-fixed']: '#ede2ff',
    ['secondary-fixed-dim']: '#d4c8e8',
    ['on-secondary-fixed']: '#1f1830',
    ['on-secondary-fixed-variant']: '#4c435e',
    ['tertiary-fixed']: '#fce8b0',
    ['tertiary-fixed-dim']: '#e8c860',
    ['on-tertiary-fixed']: '#2a1f00',
    ['on-tertiary-fixed-variant']: '#594400',
    background: '#fcfaf8',
    ['on-background']: '#1f1c18',
    ['surface-variant']: '#e4dfda',
    bg: '#fcfaf8',
    fg: '#1f1c18',
    border: '#ccc6c0',
    success: '#16a34a',
    ['success-container']: '#dafbe3',
    accent: '#665e77',
    ['primary-light']: '#7c6bb0',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '40px',
        fontWeight: '700',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '1.3',
        letterSpacing: '-0.01em',
      },
      subheading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading4: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading5: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      heading6: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '14px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      body: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
    expressive: {
      display: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '40px',
        fontWeight: '700',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '1.4',
      },
      heading4: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '1.5',
      },
      heading5: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '1.6',
      },
      heading6: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '14px',
        fontWeight: '600',
        lineHeight: '1.6',
      },
      body: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '18px',
        fontWeight: '400',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '20px',
    containerMax: '720px',
    panelNav: '260px',
    panelExplorer: '320px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.375rem',
    md: '0.5rem',
    lg: '0.625rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
