import type { ThemeDefinition } from '@open-edu/design-system';

export const nocturnal: ThemeDefinition = {
  id: 'nocturnal',
  name: 'OpenEdu Nocturnal',
  description:
    'Dark mode with deep focus. Minimalist design with glassmorphism and neon accent glows.',
  colors: {
    surface: '#151219',
    ['surface-dim']: '#151219',
    ['surface-bright']: '#3c373f',
    ['surface-container-lowest']: '#100d14',
    ['surface-container-low']: '#1e1a21',
    ['surface-container']: '#221e25',
    ['surface-container-high']: '#2c2830',
    ['surface-container-highest']: '#37333b',
    ['on-surface']: '#e8e0ea',
    ['on-surface-variant']: '#cdc3d4',
    ['inverse-surface']: '#e8e0ea',
    ['inverse-on-surface']: '#332f37',
    outline: '#978d9d',
    ['outline-variant']: '#4b4452',
    ['surface-tint']: '#dab9ff',
    primary: '#dab9ff',
    ['on-primary']: '#460283',
    ['primary-container']: '#bb86fc',
    ['on-primary-container']: '#4c0f89',
    ['inverse-primary']: '#7743b5',
    secondary: '#46f5e0',
    ['on-secondary']: '#003731',
    ['secondary-container']: '#00d8c4',
    ['on-secondary-container']: '#005950',
    tertiary: '#d4ca38',
    ['on-tertiary']: '#353200',
    ['tertiary-container']: '#aba200',
    ['on-tertiary-container']: '#3b3700',
    error: '#ffb4ab',
    ['on-error']: '#690005',
    ['error-container']: '#93000a',
    ['on-error-container']: '#ffdad6',
    ['primary-fixed']: '#eedbff',
    ['primary-fixed-dim']: '#dab9ff',
    ['on-primary-fixed']: '#2a0053',
    ['on-primary-fixed-variant']: '#5e289b',
    ['secondary-fixed']: '#4ffbe6',
    ['secondary-fixed-dim']: '#17deca',
    ['on-secondary-fixed']: '#00201c',
    ['on-secondary-fixed-variant']: '#005048',
    ['tertiary-fixed']: '#f1e752',
    ['tertiary-fixed-dim']: '#d4ca38',
    ['on-tertiary-fixed']: '#1e1c00',
    ['on-tertiary-fixed-variant']: '#4d4800',
    background: '#151219',
    ['on-background']: '#e8e0ea',
    ['surface-variant']: '#37333b',
    bg: '#151219',
    fg: '#e8e0ea',
    border: '#4b4452',
    success: '#16a34a',
    ['success-container']: '#dafbe3',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Inter',
        fontSize: '48px',
        fontWeight: '700',
        lineHeight: '56px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter',
        fontSize: '32px',
        fontWeight: '650',
        lineHeight: '40px',
        letterSpacing: '-0.01em',
      },
      subheading: {
        fontFamily: 'Inter',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '32px',
      },
      heading3: { fontFamily: 'Inter', fontSize: '20px', fontWeight: '600', lineHeight: '28px' },
      heading4: { fontFamily: 'Inter', fontSize: '18px', fontWeight: '600', lineHeight: '26px' },
      heading5: { fontFamily: 'Inter', fontSize: '16px', fontWeight: '600', lineHeight: '24px' },
      heading6: { fontFamily: 'Inter', fontSize: '14px', fontWeight: '600', lineHeight: '20px' },
      body: {
        fontFamily: 'Inter',
        fontSize: '14px',
        fontWeight: '420',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Inter',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '20px',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Inter',
        fontSize: '48px',
        fontWeight: '700',
        lineHeight: '56px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter',
        fontSize: '20px',
        fontWeight: '650',
        lineHeight: '28px',
      },
      subheading: {
        fontFamily: 'Inter',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '32px',
      },
      heading3: { fontFamily: 'Inter', fontSize: '18px', fontWeight: '600', lineHeight: '26px' },
      heading4: { fontFamily: 'Inter', fontSize: '16px', fontWeight: '600', lineHeight: '24px' },
      heading5: { fontFamily: 'Inter', fontSize: '14px', fontWeight: '600', lineHeight: '22px' },
      heading6: { fontFamily: 'Inter', fontSize: '12px', fontWeight: '600', lineHeight: '20px' },
      body: {
        fontFamily: 'Inter',
        fontSize: '16px',
        fontWeight: '420',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Inter',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '20px',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
  },
  spacing: {
    base: '4px',
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '20px',
    marginDesktop: '24px',
    marginMobile: '24px',
    containerMax: '720px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.25rem',
    DEFAULT: '0.625rem',
    md: '0.875rem',
    lg: '1.125rem',
    xl: '1.5rem',
    full: '9999px',
  },
};
