import type { ThemeDefinition } from '@open-edu/design-system';

export const nocturnal: ThemeDefinition = {
  id: 'nocturnal',
  name: 'OpenEdu Dark',
  description: 'Calm dark theme for deep focus, night sessions, and eye-strain reduction.',
  colors: {
    surface: '#151219',
    'surface-dim': '#151219',
    'surface-bright': '#3c373f',
    'surface-container-lowest': '#100d14',
    'surface-container-low': '#1e1a21',
    'surface-container': '#221e25',
    'surface-container-high': '#2c2830',
    'surface-container-highest': '#37333b',
    'on-surface': '#e8e0ea',
    'on-surface-variant': '#cdc3d4',
    'inverse-surface': '#e8e0ea',
    'inverse-on-surface': '#332f37',
    outline: '#978d9d',
    'outline-variant': '#4b4452',
    'surface-tint': '#d4c4ff',
    primary: '#d4c4ff',
    'on-primary': '#2a104d',
    'primary-container': '#5d4a8a',
    'on-primary-container': '#ede2ff',
    'inverse-primary': '#5d4a8a',
    secondary: '#cac2d0',
    'on-secondary': '#332f37',
    'secondary-container': '#4b4452',
    'on-secondary-container': '#e8e0ea',
    tertiary: '#b0a9b0',
    'on-tertiary': '#332f37',
    'tertiary-container': '#42424a',
    'on-tertiary-container': '#e0e0e8',
    error: '#ffb4ab',
    'on-error': '#690005',
    'error-container': '#93000a',
    'on-error-container': '#ffdad6',
    'primary-fixed': '#ede2ff',
    'primary-fixed-dim': '#d4c4ff',
    'on-primary-fixed': '#2a104d',
    'on-primary-fixed-variant': '#5d4a8a',
    'secondary-fixed': '#ede2ff',
    'secondary-fixed-dim': '#cac2d0',
    'on-secondary-fixed': '#1f1830',
    'on-secondary-fixed-variant': '#4c435e',
    'tertiary-fixed': '#e0e0e8',
    'tertiary-fixed-dim': '#b0a9b0',
    'on-tertiary-fixed': '#1a1a22',
    'on-tertiary-fixed-variant': '#4a4848',
    background: '#151219',
    'on-background': '#e8e0ea',
    'surface-variant': '#37333b',
    bg: '#151219',
    fg: '#e8e0ea',
    border: '#4b4452',
    success: '#4ade80',
    'success-container': '#052e16',
    'on-success': '#ffffff',
    'on-success-container': '#7fff9e',
    accent: '#b0a3c0',
    'primary-light': '#d4c4ff',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '48px',
        fontWeight: '700',
        lineHeight: '56px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '32px',
        fontWeight: '600',
        lineHeight: '40px',
        letterSpacing: '-0.01em',
      },
      subheading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '32px',
      },
      heading3: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading4: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      heading5: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '17px',
        fontWeight: '600',
        lineHeight: '24px',
      },
      heading6: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '20px',
      },
      body: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '48px',
        fontWeight: '700',
        lineHeight: '56px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      subheading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '32px',
      },
      heading3: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      heading4: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '24px',
      },
      heading5: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '14px',
        fontWeight: '600',
        lineHeight: '22px',
      },
      heading6: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '12px',
        fontWeight: '600',
        lineHeight: '20px',
      },
      body: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '16px',
        fontWeight: '400',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
  },
  spacing: {
    base: '4px',
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '20px',
    marginDesktop: '24px',
    marginMobile: '24px',
    containerMax: '720px',
    panelNav: '260px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.25rem',
    DEFAULT: '0.625rem',
    md: '0.875rem',
    lg: '1.125rem',
    xl: '1.5rem',
    full: '9999px',
  },
};
