import { palette } from '@open-edu/design-system';
import type { ThemeDefinition } from '@open-edu/design-system';

export const sylvanWorkspace: ThemeDefinition = {
  id: 'sylvan-workspace',
  name: 'Sylvan Workspace',
  description:
    'Warm, organic learning environment inspired by a forest sanctuary. Earth tones and serif typography for deep reading.',
  colors: {
    surface: '#f9faf6',
    ['surface-dim']: '#d9dad7',
    ['surface-bright']: '#f9faf6',
    ['surface-container-lowest']: palette.white,
    ['surface-container-low']: '#f3f4f0',
    ['surface-container']: '#edeeea',
    ['surface-container-high']: '#e7e9e5',
    ['surface-container-highest']: '#e2e3df',
    ['on-surface']: '#1a1c1a',
    ['on-surface-variant']: '#434843',
    ['inverse-surface']: '#2e312f',
    ['inverse-on-surface']: '#f0f1ed',
    outline: '#737973',
    ['outline-variant']: '#c3c8c1',
    ['surface-tint']: '#4d6453',
    primary: '#061b0e',
    ['on-primary']: palette.white,
    ['primary-container']: '#1b3022',
    ['on-primary-container']: '#819986',
    ['inverse-primary']: '#b4cdb8',
    secondary: '#536253',
    ['on-secondary']: palette.white,
    ['secondary-container']: '#d3e4d1',
    ['on-secondary-container']: '#576757',
    tertiary: '#251207',
    ['on-tertiary']: palette.white,
    ['tertiary-container']: '#3c261a',
    ['on-tertiary-container']: '#ac8c7b',
    error: palette.red30,
    ['on-error']: palette.white,
    ['error-container']: palette.red90,
    ['on-error-container']: palette.red20,
    ['primary-fixed']: '#d0e9d4',
    ['primary-fixed-dim']: '#b4cdb8',
    ['on-primary-fixed']: '#0b2013',
    ['on-primary-fixed-variant']: '#364c3c',
    ['secondary-fixed']: '#d6e7d4',
    ['secondary-fixed-dim']: '#bacbb8',
    ['on-secondary-fixed']: '#111f13',
    ['on-secondary-fixed-variant']: '#3c4a3c',
    ['tertiary-fixed']: '#ffdbca',
    ['tertiary-fixed-dim']: '#e3bfad',
    ['on-tertiary-fixed']: '#2a170c',
    ['on-tertiary-fixed-variant']: '#5a4134',
    background: '#f9faf6',
    ['on-background']: '#1a1c1a',
    ['surface-variant']: '#e2e3df',
    bg: '#f9faf6',
    fg: '#1a1c1a',
    border: '#c3c8c1',
    success: '#16a34a',
    ['success-container']: '#dafbe3',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '40px',
        fontWeight: '700',
        lineHeight: '48px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Source Serif 4',
        fontSize: '32px',
        fontWeight: '700',
        lineHeight: '38px',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '36px',
      },
      heading3: {
        fontFamily: 'Source Serif 4',
        fontSize: '22px',
        fontWeight: '600',
        lineHeight: '30px',
      },
      heading4: {
        fontFamily: 'Source Serif 4',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading5: {
        fontFamily: 'Source Serif 4',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      heading6: {
        fontFamily: 'Source Serif 4',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      body: {
        fontFamily: 'Literata',
        fontSize: '16px',
        fontWeight: '420',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '16px',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '40px',
        fontWeight: '700',
        lineHeight: '48px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '36px',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '36px',
      },
      heading3: {
        fontFamily: 'Source Serif 4',
        fontSize: '22px',
        fontWeight: '600',
        lineHeight: '30px',
      },
      heading4: {
        fontFamily: 'Source Serif 4',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading5: {
        fontFamily: 'Source Serif 4',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading6: {
        fontFamily: 'Source Serif 4',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      body: {
        fontFamily: 'Literata',
        fontSize: '18px',
        fontWeight: '420',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '16px',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '20px',
    containerMax: '720px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.375rem',
    md: '0.5rem',
    lg: '0.625rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
