import type { ThemeDefinition } from '@open-edu/design-system';

export const sylvanWorkspace: ThemeDefinition = {
  id: 'sylvan-workspace',
  name: 'Sylvan Workspace',
  description:
    'Warm, organic learning environment inspired by a forest sanctuary. Earth tones and serif typography for deep reading.',
  colors: {
    surface: '#faf8f4',
    'surface-dim': '#e4e1dc',
    'surface-bright': '#fefcf8',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f4f2ec',
    'surface-container': '#efede6',
    'surface-container-high': '#e9e6df',
    'surface-container-highest': '#e4e0d9',
    'on-surface': '#1c1b17',
    'on-surface-variant': '#494640',
    'inverse-surface': '#31302c',
    'inverse-on-surface': '#f4f2ee',
    outline: '#76736e',
    'outline-variant': '#c6c2bc',
    'surface-tint': '#1a301a',
    primary: '#1a301a',
    'on-primary': '#ffffff',
    'primary-container': '#c4dcc4',
    'on-primary-container': '#0a1a0a',
    'inverse-primary': '#b4d4b4',
    secondary: '#5e6e5a',
    'on-secondary': '#ffffff',
    'secondary-container': '#d5e4d1',
    'on-secondary-container': '#2a3d24',
    tertiary: '#3a2a1a',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#6a5a4a',
    'on-tertiary-container': '#d4c4b0',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#c4dcc4',
    'primary-fixed-dim': '#a4c4a4',
    'on-primary-fixed': '#0a1a0a',
    'on-primary-fixed-variant': '#2a402a',
    'secondary-fixed': '#d5e4d1',
    'secondary-fixed-dim': '#b8c8b4',
    'on-secondary-fixed': '#1a2d14',
    'on-secondary-fixed-variant': '#3a4d34',
    'tertiary-fixed': '#e4d4c0',
    'tertiary-fixed-dim': '#c4b4a0',
    'on-tertiary-fixed': '#2a1a0a',
    'on-tertiary-fixed-variant': '#4a3a2a',
    background: '#faf8f4',
    'on-background': '#1c1b17',
    'surface-variant': '#e4e0d9',
    bg: '#faf8f4',
    fg: '#1c1b17',
    border: '#c6c2bc',
    success: '#16a34a',
    'success-container': '#dafbe3',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '40px',
        fontWeight: '700',
        lineHeight: '48px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Source Serif 4',
        fontSize: '32px',
        fontWeight: '700',
        lineHeight: '38px',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '36px',
      },
      heading3: {
        fontFamily: 'Source Serif 4',
        fontSize: '22px',
        fontWeight: '600',
        lineHeight: '30px',
      },
      heading4: {
        fontFamily: 'Source Serif 4',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading5: {
        fontFamily: 'Source Serif 4',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      heading6: {
        fontFamily: 'Source Serif 4',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      body: {
        fontFamily: 'Literata',
        fontSize: '16px',
        fontWeight: '420',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '16px',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Source Serif 4',
        fontSize: '40px',
        fontWeight: '700',
        lineHeight: '48px',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '36px',
      },
      subheading: {
        fontFamily: 'Source Serif 4',
        fontSize: '28px',
        fontWeight: '600',
        lineHeight: '36px',
      },
      heading3: {
        fontFamily: 'Source Serif 4',
        fontSize: '22px',
        fontWeight: '600',
        lineHeight: '30px',
      },
      heading4: {
        fontFamily: 'Source Serif 4',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading5: {
        fontFamily: 'Source Serif 4',
        fontSize: '18px',
        fontWeight: '600',
        lineHeight: '28px',
      },
      heading6: {
        fontFamily: 'Source Serif 4',
        fontSize: '16px',
        fontWeight: '600',
        lineHeight: '26px',
      },
      body: {
        fontFamily: 'Literata',
        fontSize: '18px',
        fontWeight: '420',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Hanken Grotesk',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '16px',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '20px',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '20px',
    containerMax: '720px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.125rem',
    DEFAULT: '0.375rem',
    md: '0.5rem',
    lg: '0.625rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
