import { palette } from '@open-edu/design-system';
import type { ThemeDefinition } from '@open-edu/design-system';

export const zen: ThemeDefinition = {
  id: 'zen',
  name: 'Zen',
  description: 'Minimalist light theme with reduced visual noise.',
  colors: {
    surface: palette.stone95,
    'surface-dim': palette.stone85,
    'surface-bright': palette.white,
    'surface-container-lowest': palette.white,
    'surface-container-low': palette.stone92,
    'surface-container': palette.stone88,
    'surface-container-high': palette.stone85,
    'surface-container-highest': palette.stone82,
    'on-surface': palette.stone10,
    'on-surface-variant': palette.stone35,
    'inverse-surface': palette.stone20,
    'inverse-on-surface': palette.stone95,
    outline: palette.stone50,
    'outline-variant': palette.stone75,
    'surface-tint': palette.stone40,
    primary: palette.stone40,
    'on-primary': palette.white,
    'primary-container': palette.stone81,
    'on-primary-container': palette.stone10,
    'inverse-primary': palette.stone70,
    secondary: palette.stone45,
    'on-secondary': palette.white,
    'secondary-container': palette.stone90,
    'on-secondary-container': palette.stone15,
    tertiary: palette.gray55,
    'on-tertiary': palette.white,
    'tertiary-container': palette.gray70,
    'on-tertiary-container': palette.gray25,
    error: palette.red50,
    'on-error': palette.white,
    'error-container': palette.red93,
    'on-error-container': palette.red12,
    'primary-fixed': palette.stone89,
    'primary-fixed-dim': palette.stone81,
    'on-primary-fixed': palette.stone10,
    'on-primary-fixed-variant': palette.stone30,
    'secondary-fixed': palette.stone90,
    'secondary-fixed-dim': palette.stone80,
    'on-secondary-fixed': palette.stone10,
    'on-secondary-fixed-variant': palette.stone15,
    'tertiary-fixed': palette.gray72,
    'tertiary-fixed-dim': palette.gray60,
    'on-tertiary-fixed': palette.gray15,
    'on-tertiary-fixed-variant': palette.gray25,
    background: palette.stone95,
    'on-background': palette.stone10,
    'surface-variant': palette.stone85,
  },
  typography: {
    display: {
      fontFamily: 'Inter',
      fontSize: '44px',
      fontWeight: '300',
      lineHeight: '1.1',
      letterSpacing: '-0.02em',
    },
    headlineLg: {
      fontFamily: 'Inter',
      fontSize: '28px',
      fontWeight: '400',
      lineHeight: '1.3',
      letterSpacing: '-0.01em',
    },
    headlineMd: { fontFamily: 'Inter', fontSize: '22px', fontWeight: '400', lineHeight: '1.3' },
    title: { fontFamily: 'Inter', fontSize: '20px', fontWeight: '500', lineHeight: '1.3' },
    bodyLg: { fontFamily: 'Inter', fontSize: '17px', fontWeight: '300', lineHeight: '1.7' },
    bodyMd: { fontFamily: 'Inter', fontSize: '14px', fontWeight: '400', lineHeight: '1.5' },
    label: {
      fontFamily: 'Inter',
      fontSize: '11px',
      fontWeight: '500',
      lineHeight: '1.0',
      letterSpacing: '0.04em',
    },
    caption: { fontFamily: 'Inter', fontSize: '13px', fontWeight: '300', lineHeight: '1.5' },
    mono: { fontFamily: 'JetBrains Mono', fontSize: '13px', fontWeight: '400', lineHeight: '1.6' },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '16px',
    containerMax: '720px',
    panelNav: '240px',
    panelExplorer: '300px',
  },
  radii: { sm: '0px', DEFAULT: '0px', md: '0px', lg: '0px', xl: '0px', full: '9999px' },
};
