import type { ThemeDefinition } from '@open-edu/design-system';

export const zen: ThemeDefinition = {
  id: 'zen',
  name: 'OpenEdu Zen',
  description: 'Reduced-stimulation theme for contemplative reading and low-arousal accessibility.',
  colors: {
    surface: '#fcfaf8',
    'surface-dim': '#e2dfdc',
    'surface-bright': '#fefcf8',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f6f4f0',
    'surface-container': '#f0eeea',
    'surface-container-high': '#eae7e3',
    'surface-container-highest': '#e4e1dd',
    'on-surface': '#1f1c1a',
    'on-surface-variant': '#484642',
    'inverse-surface': '#32302e',
    'inverse-on-surface': '#f4f2ef',
    outline: '#75736e',
    'outline-variant': '#c6c3bd',
    'surface-tint': '#8a8294',
    primary: '#6f667e',
    'on-primary': '#ffffff',
    'primary-container': '#d4cfdc',
    'on-primary-container': '#2a2630',
    'inverse-primary': '#d4cfdc',
    secondary: '#726e68',
    'on-secondary': '#ffffff',
    'secondary-container': '#d4d0c8',
    'on-secondary-container': '#2a2824',
    tertiary: '#727070',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#cccaca',
    'on-tertiary-container': '#2a2a28',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#e8e4e6',
    'primary-fixed-dim': '#d4cfdc',
    'on-primary-fixed': '#1c1a28',
    'on-primary-fixed-variant': '#4a4654',
    'secondary-fixed': '#d4d0c8',
    'secondary-fixed-dim': '#b8b4ac',
    'on-secondary-fixed': '#22201c',
    'on-secondary-fixed-variant': '#3a3832',
    'tertiary-fixed': '#e0dedc',
    'tertiary-fixed-dim': '#c4c2c0',
    'on-tertiary-fixed': '#2a2a28',
    'on-tertiary-fixed-variant': '#4a4848',
    background: '#fcfaf8',
    'on-background': '#1f1c1a',
    'surface-variant': '#e4e1dd',
    bg: '#fcfaf8',
    fg: '#1f1c1a',
    border: '#c6c3bd',
    success: '#16a34a',
    'success-container': '#dafbe3',
    'on-success': '#ffffff',
    'on-success-container': '#2c4a32',
    accent: '#726e68',
    'primary-light': '#a89fb2',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '44px',
        fontWeight: '300',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '28px',
        fontWeight: '500',
        lineHeight: '1.3',
        letterSpacing: '-0.01em',
      },
      subheading: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '22px',
        fontWeight: '400',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '18px',
        fontWeight: '400',
        lineHeight: '1.4',
      },
      heading4: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '16px',
        fontWeight: '400',
        lineHeight: '1.4',
      },
      heading5: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '14px',
        fontWeight: '500',
        lineHeight: '1.5',
      },
      heading6: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '12px',
        fontWeight: '500',
        lineHeight: '1.5',
      },
      body: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '14px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
    expressive: {
      display: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '44px',
        fontWeight: '300',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '22px',
        fontWeight: '400',
        lineHeight: '1.3',
      },
      heading3: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '18px',
        fontWeight: '400',
        lineHeight: '1.4',
      },
      heading4: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '16px',
        fontWeight: '500',
        lineHeight: '1.5',
      },
      heading5: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '14px',
        fontWeight: '500',
        lineHeight: '1.6',
      },
      heading6: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '12px',
        fontWeight: '500',
        lineHeight: '1.6',
      },
      body: {
        fontFamily: '"Source Serif 4", Georgia, ui-serif, serif',
        fontSize: '16px',
        fontWeight: '400',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: '"JetBrains Mono", ui-monospace, monospace',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '16px',
    containerMax: '720px',
    panelNav: '260px',
    panelExplorer: '300px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: {
    sm: '0.25rem',
    DEFAULT: '0.375rem',
    md: '0.5rem',
    lg: '0.625rem',
    xl: '0.75rem',
    full: '9999px',
  },
};
