import type { ThemeDefinition } from '@open-edu/design-system';

export const zen: ThemeDefinition = {
  id: 'zen',
  name: 'Zen',
  description: 'Minimalist light theme with reduced visual noise.',
  colors: {
    surface: '#fcfaf8',
    'surface-dim': '#e2dfdc',
    'surface-bright': '#fefcf8',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f6f4f0',
    'surface-container': '#f0eeea',
    'surface-container-high': '#eae7e3',
    'surface-container-highest': '#e4e1dd',
    'on-surface': '#1f1c1a',
    'on-surface-variant': '#484642',
    'inverse-surface': '#32302e',
    'inverse-on-surface': '#f4f2ef',
    outline: '#75736e',
    'outline-variant': '#c6c3bd',
    'surface-tint': '#5d5a54',
    primary: '#5d5a54',
    'on-primary': '#ffffff',
    'primary-container': '#c6c2bc',
    'on-primary-container': '#1c1a16',
    'inverse-primary': '#c6c2bc',
    secondary: '#726e68',
    'on-secondary': '#ffffff',
    'secondary-container': '#d4d0c8',
    'on-secondary-container': '#2a2824',
    tertiary: '#727070',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#cccaca',
    'on-tertiary-container': '#2a2a28',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#e8e4de',
    'primary-fixed-dim': '#c6c2bc',
    'on-primary-fixed': '#1c1a16',
    'on-primary-fixed-variant': '#4a4842',
    'secondary-fixed': '#d4d0c8',
    'secondary-fixed-dim': '#b8b4ac',
    'on-secondary-fixed': '#22201c',
    'on-secondary-fixed-variant': '#3a3832',
    'tertiary-fixed': '#e0dedc',
    'tertiary-fixed-dim': '#c4c2c0',
    'on-tertiary-fixed': '#2a2a28',
    'on-tertiary-fixed-variant': '#4a4848',
    background: '#fcfaf8',
    'on-background': '#1f1c1a',
    'surface-variant': '#e4e1dd',
    bg: '#fcfaf8',
    fg: '#1f1c1a',
    border: '#c6c3bd',
    success: '#16a34a',
    'success-container': '#dafbe3',
  },
  typography: {
    productive: {
      display: {
        fontFamily: 'Inter',
        fontSize: '44px',
        fontWeight: '300',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter',
        fontSize: '28px',
        fontWeight: '500',
        lineHeight: '1.3',
        letterSpacing: '-0.01em',
      },
      subheading: {
        fontFamily: 'Inter',
        fontSize: '22px',
        fontWeight: '400',
        lineHeight: '1.3',
      },
      heading3: { fontFamily: 'Inter', fontSize: '18px', fontWeight: '400', lineHeight: '1.4' },
      heading4: { fontFamily: 'Inter', fontSize: '16px', fontWeight: '400', lineHeight: '1.4' },
      heading5: { fontFamily: 'Inter', fontSize: '14px', fontWeight: '500', lineHeight: '1.5' },
      heading6: { fontFamily: 'Inter', fontSize: '12px', fontWeight: '500', lineHeight: '1.5' },
      body: {
        fontFamily: 'Inter',
        fontSize: '14px',
        fontWeight: '420',
        lineHeight: '1.6',
      },
      label: {
        fontFamily: 'Inter',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
    expressive: {
      display: {
        fontFamily: 'Inter',
        fontSize: '44px',
        fontWeight: '300',
        lineHeight: '1.1',
        letterSpacing: '-0.02em',
      },
      heading: {
        fontFamily: 'Inter',
        fontSize: '20px',
        fontWeight: '600',
        lineHeight: '1.3',
      },
      subheading: {
        fontFamily: 'Inter',
        fontSize: '22px',
        fontWeight: '400',
        lineHeight: '1.3',
      },
      heading3: { fontFamily: 'Inter', fontSize: '18px', fontWeight: '400', lineHeight: '1.4' },
      heading4: { fontFamily: 'Inter', fontSize: '16px', fontWeight: '500', lineHeight: '1.5' },
      heading5: { fontFamily: 'Inter', fontSize: '14px', fontWeight: '500', lineHeight: '1.6' },
      heading6: { fontFamily: 'Inter', fontSize: '12px', fontWeight: '500', lineHeight: '1.6' },
      body: {
        fontFamily: 'Inter',
        fontSize: '17px',
        fontWeight: '420',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      label: {
        fontFamily: 'Inter',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: '1.0',
        letterSpacing: '0.08em',
      },
      caption: {
        fontFamily: 'Inter',
        fontSize: '13px',
        fontWeight: '420',
        lineHeight: '1.5',
      },
      code: {
        fontFamily: 'JetBrains Mono',
        fontSize: '13px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  spacing: {
    base: '8px',
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    marginDesktop: '48px',
    marginMobile: '16px',
    containerMax: '720px',
    panelNav: '240px',
    panelExplorer: '300px',
    readingWidth: '68ch',
    paragraphSpacing: '1.5rem',
  },
  radii: { sm: '0px', DEFAULT: '0px', md: '0px', lg: '0px', xl: '0px', full: '9999px' },
};
