export type DictionaryEntry = Record<string, string>
export type DictionaryProvider = Record<string, never>
export type LearningContext = Record<string, never>
export type ExplanationRequest = Record<string, never>
export type ExplanationStyle = string
export type AIResponse = { content: string }
export type AIProvider = Record<string, never>
export type ContextProvider = Record<string, never>
export type ConversationMessage = { role: string; content: string }
export type ConversationStore = Record<string, never>
export type CacheEntry = Record<string, never>
export type CacheProvider = Record<string, never>
